config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

  get '/spots/new', to: 'spots#new'
  post '/spots/new', to: 'spots#new'

  post '/spots/create', to: 'spots#create'

  get '/spots', to: 'spots#show'

  post '/spots/search', to: 'spots#search'
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :spots
  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  layout "application"
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def show
    @spot = Spot.find(params[:id])
  end

  def index
    @spot = Spot.all
  end

  def new
    if current_user == nil
      flash[:error] = "Log in to continue"
      redirect_to root_path
    else
      @spot = Spot.new
    end
  end

  def create
    @spot = Spot.new
    @spot.address = params[:spot][:address]
    @spot.beds = params[:spot][:beds]
    @spot.baths = params[:spot][:baths]
    @spot.description = params[:spot][:description]
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    @spot.owner = @current_user.uid

    if @spot.save
      redirect_to spots_path(:id => @spot.id)
    else
      flash[:error] = @spot.errors.full_messages.to_sentence
      redirect_to spots_new_path
    end
  end

  def search
    @spot = Spot.new
    @spot.beds = params[:spot][:beds]
    @spot.price = params[:spot][:price]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/show.html.erb
<h2 class ="text-primary" style="color: white; text-align: center;">BearHouse</h2>

<h4 class="text-primary" style="color: white; text-align: center;">Let us help you find your next great home!</h4>
<br>
<br>
<div style="text-align: center;" class="container">
  <div class="row">
    <div name="search" class="span12">

      <%= simple_form_for Spot.new, :url => spots_new_path,
        wrapper: :inline_form,
        html: {class: 'form-inline'} do |f| %>
        <%= f.button :submit, 'Create New Listing' %>
      <% end %>

      <%= simple_form_for Spot.new, :url => spots_search_path,
        wrapper: :inline_form,
        html: {class: 'form-inline'} do |f| %>
        <%= f.input :beds, prompt: "Beds", :collection => ['Studio','1','2','3','4+'] %>
        <%= f.input :price, prompt: "Price",
        :collection => ['Less than $800', '$800 to $1000', '$1000-$1200', '$1200-$1500', 'More than $1500'] %>
        <%= f.button :submit, 'Search' %>
      <% end %>

<<<<<<< HEAD
=======
        <input class="span5" type="text" placeholder="Rooms">
        <input class="span5" type="text" placeholder="Price">
        <input class="span5" type="text" placeholder="Location">
        <button type="submit" class="btn btn-primary">Search</button>
      </form>
>>>>>>> fixedAlert
    </div>


  </div>

</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bear House</title>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag    "default", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "default", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background: url('../images/A_E_S_T_H_E_T_I_C.png') no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;">
<div style="text-align: right;">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>
<main role="main">
  <%= render partial: "layouts/flash_messages", flash: flash %>
</main>

<%= yield %>
</body>
</html>

app/views/spots/create.html.erb
<h1>Sessions#create</h1>
<p>Find me in app/views/sessions/create.html.erb</p>

app/views/spots/new.html.erb
Create New Listing
<%= simple_form_for @spot, :url => spots_create_path do |f| %>
  <%= f.input :address %>
  <%= f.input :beds %>
  <%= f.input :baths %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/spots/show.html.erb
<p>Address: <%= @spot.address%></p>
<p>Beds: <%= @spot.beds%></p>
<p>Baths: <%= @spot.baths%></p>
<p>Description: <%= @spot.description%></p>